"""
Django settings for moneyball project.

Generated by "django-admin startproject" using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

pip install --upgrade pip && pip install -r requirements.txt
gunicorn --workers=1 --threads=3 moneyball.wsgi:application
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-rn9i)qy0w(aokm0arqnmvaeco^i9e5g!h4736&chx(13qq-9al"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "https://moneyball-ai.onrender.com,https://localhost:8000,https://127.0.0.1:8000").split(",")

BED_URL_DOMAIN = "https://moneyball-ai.onrender.com"
SOCKET_STREAM_URL_DOMAIN = "https://moneyball-ai-socket-service.onrender.com"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "admin_extra_buttons",
    "import_export",

    "system_conf",
    "stock",
    "account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "moneyball.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "moneyball.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse("postgresql://moneyball_db_1_user:Xb8mFjnesziBYKTDH5eqL1mFhyuTFCr0@dpg-crvruro8fa8c73dtc1t0-a/moneyball_db_1", conn_max_age=0),
} if os.getenv('SERVER_DB', False) else {
    'default': dj_database_url.parse("postgresql://moneyball_db_1_user:Xb8mFjnesziBYKTDH5eqL1mFhyuTFCr0@dpg-crvruro8fa8c73dtc1t0-a.singapore-postgres.render.com/moneyball_db_1", conn_max_age=0),
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Broker Detail
BROKER_PIN = int(os.getenv("BROKER_PIN", '0000'))
BROKER_USER_ID = os.getenv("BROKER_USER_ID", 'User-Id Required')
BROKER_API_KEY = os.getenv("BROKER_API_KEY", 'Api Key Required')
BROKER_TOTP_KEY = os.getenv("BROKER_TOTP_KEY", 'TOTP Key required')

SENGDRID_FROM_EMAIL = 'hapbrothers@gmail.com'
SENGDRID_FROM_NAME = 'MoneyBall.ai'
SENDGRID_API_KEY = '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'


# Global Variable
global broker_connection, account_connections, entry_holder

import pyotp
from SmartApi import SmartConnect
connection = SmartConnect(api_key=BROKER_API_KEY)
connection.generateSession(BROKER_USER_ID, BROKER_PIN, totp=pyotp.TOTP(BROKER_TOTP_KEY).now())

broker_connection = connection
account_connections = {}
entry_holder = {}